#! /bin/env tclsh

# Copyright (C) 2011-2012, Nathan Coulter and others 

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 2 of the License.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

module c
#TODO: see about using tclsubs in stdioctcl
namespace eval libtcl {
    variable stubs 0
}
module libtcl

eval_later {
	set ::c::FLAGS [linsert $::c::FLAGS 0 -I[file join $PROJDIR gnulib tests]]
	set ::c::FLAGS [linsert $::c::FLAGS 0 -I[file join $PROJDIR include]]
	#lappend ::c::FLAGS -E

	set ::link::LIBPATH [linsert $::link::LIBPATH[set ::link::LIBPATH {}] 0 \
		[file join $::PROJDIR stdioctcl $::ARCH]]
	lappend ::link::OPTIONS lib_in_lib
	lappend ::link::SYSLIBS stdioctcl

	#lappend ::link::SYSLIBS stdioctcl
	#lappend ::link::LIBPATH [file join $PROJDIR stdioctcl $ARCH]

	#build [list tests.o test-fflush.o]
	build [list tests.o ]
}

target test tests {
	exec [info nameofexecutable] all.tcl >@stdout 2>@stderr
}

target install {} {}

