#!/bin/sh
# -*-Mode: tcl -*-
#\
exec ${TMK_TCLSH:=tclsh} "$0" "$@"
# ----------------------------------------------------------------------------
# $Id: cvsutil,v 1.1 2000/08/08 10:10:24 ag4-adm Exp $
# some utility functions for CVS
# ----------------------------------------------------------------------------
# $Log: cvsutil,v $
# Revision 1.1  2000/08/08 10:10:24  ag4-adm
# *** empty log message ***
#
# ----------------------------------------------------------------------------

# default values for CVS-related variables
if [info exists env(CVS)] {
    set CVS $env(CVS)
} else {
    set CVS [exec which cvs]
}
if [info exists env(CVSROOT)] {
    set CVSROOT $env(CVSROOT)
} else {
    set CVSROOT ""
}

# the syntax error text
set syntax {
syntax: cvsutil [-opt [value(s)] ... [--]] <cmd> <args...>

  options: 
 
    -d <repository> specify CVS repository [\$CVSROOT]

  commands: 

    modifiers <date> <pattern-list>

      returns the names of the users who have modified the repositry
      since <date>, for the specified glob-style file patterns
}


# the command dispatcher for 'history'
proc cvs {cmd args} {
    set procname cvs_$cmd
    if {[llength [info commands $procname]] == 0} {
	puts stderr "unknown cvsy command: $cmd"
	exit 1
    }
    return [uplevel 1 $procname $args]
}

# find out who committed something
proc cvs_modifiers {date args} {

    global CVSROOT CVS 
    set cmd [list $CVS -d $CVSROOT history -a -x MAR -D $date]
    set lines [split [eval exec $cmd] \n]
    set num_lines [llength $lines]

    set result {}
    foreach line $lines {

	set user [lindex $line 4]
	set file [file join [lindex $line 7] [lindex $line 6]]

	# file match?
	foreach pat $args {
	    if [string match $pat $file] {
		if {[lsearch -exact $result $user] == -1} {
		    lappend result $user
		}
		break
	    }
	}
    }
    return $result
}

# --------- begin main (only if not used from within tmk) ----------

if {![info exists ::tmk::dir]} {
    
    # parse options
    for {set i 0} {$i < $argc} {incr i} {
	set opt [lindex $argv $i]
	if {$opt == "--"} {
	    # end of options
	    incr i
	    break
	}
	if {[string index $opt 0] == "-"} {
	    switch -glob -- $opt {
		"-d" {incr i; set CVSROOT [lindex $argv $i]}
		"default" {puts stderr $syntax ; exit 1}
	    }
	} else {
	    # no option -> here comes the command
	    break
	}
    }
    
    # parse command
    set cmd [lindex $argv $i]
    switch $cmd {
	"modifiers" {
	    if {[llength $argv] < [expr $i + 2]} {
		puts stderr $syntax ; exit 1
	    }
	    puts [eval cvs modifiers [lrange $argv [expr $i + 1] end]]
	}
	"default" {
	    puts stderr $syntax ; exit 1
	}
    }
    exit 0
}
