#!/bin/sh
# -*-Mode: tcl -*-
#\
exec ${TMK_TCLSH:=tclsh} "$0" "$@"

# this script just outputs the argument words it gets

puts -nonewline "arg_tester: "
foreach x $argv {
	puts -nonewline "\[$x\] "
}
puts ""
