#! /bin/env tclsh

set auto_path [linsert $auto_path[set auto_path {}] 0 \
	[file join \
		[file dirname [file dirname [file normalize [info script]]]] \
		tclcfive \
	]
]

package require cfive

file mkdir cfive://me
file copy testdata/hypothyroid.names cfive://me
file copy testdata/hypothyroid.data cfive://me
cd cfive://me
cfive_stdio stdout $fh
#puts "nuts"
cfive -f hypothyroid -r
#close $fh
set fh [open res2 w]
cfive_stdio stdout $fh
cfive -f hypothyroid -r

seek $fh 0
set data [read $fh]
puts "data: $data"
