#! /bin/env tclsh

# Copyright (C) 2011-2012, Nathan Coulter and others 

#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 2 of the License.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

package require fileutil

module c
module tcl

build [list libstdioctcl.a libstdioctcl.so]

set ::link::MAKE_LIB 0
set ::link::MAKE_SHLIB 0

lappend ::link::OPTIONS lib_in_lib

set ::c::FLAGS [linsert $::c::FLAGS[set ::c::FLAGS {}] 0 \
	-I[file join $PROJDIR include]]
lappend ::HEADERS {*}[glob [file join $PROJDIR include *]]
lappend ::LIBRARIES libstdioctcl.so

link::make_lib libstdioctcl.a stdioctcl.o
link::make_shlib libstdioctcl.so stdioctcl.o
depend test [list libstdioctcl.a libstdioctcl.so]

