#! /bin/env tclsh

module c
module tclext

set ::link::MAKE_LIB 0
set ::link::MAKE_SHLIB 0

lappend ::link::OPTIONS lib_in_lib
lappend ::link::SYSLIBS cfive
lappend ::LIBRARIES {*}[glob *.tcl] libtclcfive.so

link::make_shlib libtclcfive.so tclcfive.o 

build libtclcfive.so
depend test libtclcfive.so
