#! /bin/env tclsh

module am

lappend PROGRAMS prog1 src/prog2
lappend HEADERS header1.h src/header2.h
lappend HEADERS {header1a.h dest pkgdir}
lappend HEADERS {src/header2a.h dest pkgdir}
lappend LIBRARIES libmyfakelib1.so src/libmyfakelib2.so
lappend LIBRARIES {libmyfakelib1a.so dest pkgdir} \
	{src/libmyfakelib2a.so dest pkgdir}

